### ISSUE TITLE
Schedule for on month after issue

### ISSUE THREAD

**Issue by tarikmalian** [mattpat/node-schedule#48]
I'm using node-schedule in order to fire an action one month later like this:

var schedule = require('node-schedule');
var data_schedule = new Date(2014, 5, 27, 15, 47, 2);

var j = schedule.scheduleJob(data_schedule, function(){
        console.log('Na hora certa');
        });

If I change the month from 5 to 4 (May) it's work, but otherwise it's fire a command instantly.

Why these behavior ?

Thanks

**Comment by santigimeno** [comment]
This should've been resolved with commit https://github.com/mattpat/node-schedule/commit/54060098678432416ddcb7208f7f54c4daddf891.

@hellowin @stensrud Could you check with the latest version?

**Comment by tejasmanohar** [comment]
I just checked, and it's now resolved. This issue hasn't been commented on since fall of 2014, so getting responses is going to be tough :cry:
