### ISSUE TITLE
Job schedules immediately rather than on specified date

### ISSUE THREAD

**Issue by jasonVeld** [mattpat/node-schedule#55]
Appears in this simple example, that a job scheduled for later date is run immediately instead. As far as I know, there's nothing wrong with the js code supplying the job callback function.

var deferred = require('deferred');
var schedule = require('node-schedule');
 
var handler = function(param) {
     return function() {
        console.log("Handler running");
     }
};
 
var h = handler('something');
console.log("handler type: " + typeof(h));
console.log("scheduling job... ");
schedule.scheduleJob(new Date('15 October 2014'), h );
 
 
 
OUTPUT:
( "Handler running" shouldn't appear. )

 
handler type: function
scheduling job...
Handler running

-----------------

And curious behavior here:
var handler_1 = function() { console.log("Handler 1 running") };
var start_date = new Date();
start_date.setTime(start_date.getTime() + (10 * 1000));  // start job 10 seconds from now.
schedule.scheduleJob(start_date, handler_1 );
schedule.scheduleJob(new Date(2015, 11, 21, 5, 30, 0), function() { console.log("This is a test.")} );

The first job doesn't run immediately but 10 seconds later as it should.
But the second job executes after the first, when it shouldn't run at all (until next year).

??
 
Odd that with 1900+ downloads the last week, that someone else hasn't come across this.

Also, another tried this, with same versions for node and node-schedule, v0.10.31 and node-schedule@0.1.13, and they got the correct behavior with correct scheduled execution of the handler.

**Comment by santigimeno** [comment]
This should've been resolved with commit https://github.com/mattpat/node-schedule/commit/54060098678432416ddcb7208f7f54c4daddf891.
@jasonVeld Could you check with the latest version?

**Comment by tejasmanohar** [comment]
This is resolved. Just tested :+1: 

But please comment here if there are any issues, @jasonVeld and we'll re-open.
