### ISSUE TITLE
Scheduling recurring timezone-centric jobs?

### ISSUE THREAD

**Issue by abl** [mattpat/node-schedule#70]
Hi! I really like node-schedule so far. Trying to figure out the best way to sort this problem out.

For reasons of sanity, I keep all of my server-like systems in UTC (some with leap seconds, some without, but that's a different complaint. :)

I'd like to set up a recurring timezone-centric job; let's call it an alarm clock, because it is.

I, unfortunately, live in a DST timezone; it looks like I can't use recurrence because it'd become inaccurate whenever DST changes - the next alarm wouldn't be 24 hours in the future, it'd be one more or one less.

I could get around this by manual recurrence - schedule the job in UTC, and when the job fires, begin by scheduling the next job (and check DST, etc) - but I was wondering if there's something I'm missing that might make it easier / if I'm better off extending nextInvocationDate et al.

Thanks!

**Comment by tejasmanohar** [comment]
Tasks are currently to be scheduled on the basis of system time. If you want to add optional timezone support, feel free to PR us and I'll take a look! Till then, it seems the workaround should work just as well.

**Comment by santigimeno** [comment]
bug #34
