### ISSUE TITLE
Running a recurring every 90 minutes 

### ISSUE THREAD

**Issue by vartana** [mattpat/node-schedule#71]
How would I be able to run a  function every 90 minutes?

**Comment by tejasmanohar** [comment]
https://github.com/mattpat/node-schedule#recurrence-rule-scheduling

or even a simple `setInterval()`

**Comment by tejasmanohar** [comment]
>>> node-schedule is for time-based scheduling, not interval-based scheduling. While you can easily bend it to your will, if you only want to do something like "run this function every 5 minutes", you'll find setInterval much easier to use, and far more appropriate. But if you want to, say, "run this function at the :20 and :50 of every hour on the third Tuesday of every month," you'll find that node-schedule suits your needs better. Additionally, node-schedule has Windows support unlike true cron since the node runtime is now fully supported.

from [README.md](https://github.com/mattpat/node-schedule/blob/master/README.md)
