### ISSUE TITLE
Scheduler does not cancel my job

### ISSUE THREAD

**Issue by andela-omesanni** [mattpat/node-schedule#73]
I scheduled a job to always perform a phone call one minute from the current time. As soon as i schedule the job i then try to cancel it but it doesn't work. This is the code i use  schedule.cancelJob(job.name);

Every time i run my node js script, twilio still calls my phone even after i have specified that the job should be canceled. I will appreciate if anybody can help me with how to really cancel an already existing job. Here is some code i wrote:

```javascript
var job = schedule.scheduleJob(date, function() {
  requester.startCallProcess({
    callRequestId: callDetails.callRequestId,
    scheduledCallId: scheduledCall.key(),
    requesterId: callDetails.requesterId,
    expertId: callDetails.expertId,
    requesterPhoneNumber: callDetails.requesterPhoneNumber,
    expertPhoneNumber: callDetails.expertPhoneNumber
  });
});
schedule.cancelJob(job.name);
```

I also tried job.cancel() and that still didn't work

**Comment by tejasmanohar** [comment]
Will look at this on Sunday.

**Comment by tejasmanohar** [comment]
This is strange. Still trying to figure it out.

**Comment by santigimeno** [comment]
Can't reproduce it with v0.1.16 nor master.
@andela-omesanni Could you write a basic test that reproduces the problem for you?

**Comment by tejasmanohar** [comment]
@andela-omesanni Try to keep the test as simple as possible with basic JS + this library, removing Twilio from the picture. This will help us identify the issue *in node-schedule* and not anything else, if existent.

**Comment by tejasmanohar** [comment]
Will re-open after a basic test is provided.
