### ISSUE TITLE
Expose Job.pendingInvocations

### ISSUE THREAD

**Issue by santigimeno** [mattpat/node-schedule#74]
Hi,

Would it make sense exposing Job.pendingInvocations to better instrument this module? Adding something like this after `Job.nextInvocation` definition
```
this.pendingInvocations = function(){
  return pendingInvocations;
};
```

**Comment by tejasmanohar** [comment]
Hmm, I think you're right! Feel free to send in a PR, confirming that the tests pass, and if it follows what is declared here, I'll merge it in.

**Comment by santigimeno** [comment]
See https://github.com/mattpat/node-schedule/pull/82
