### ISSUE TITLE
Seems that tests may be failing in some timezones for month and year

### ISSUE THREAD

**Issue by jonhester** [mattpat/node-schedule#88]
See https://github.com/mattpat/node-schedule/pull/86

I think that having travis test every pull request would probably help so there is a consistent test environment.

**Comment by santigimeno** [comment]
@jonhester Can you see if https://github.com/mattpat/node-schedule/pull/89 works for you?

**Comment by santigimeno** [comment]
With this changes the tests pass for me with and without your changes

**Comment by jonhester** [comment]
Works for me. I think that it's still better to use the correct values for day and year length.

**Comment by santigimeno** [comment]
I'm not sure I agree. Imagine in the 3 months period we include July, August and September. Having July and August 31 days the test may fail. I think better be safe and use 31 days and 366 days for those tests. What do you think?

**Comment by jonhester** [comment]
Easy to test. Just change the date.

**Comment by tejasmanohar** [comment]
#89

**Comment by tejasmanohar** [comment]
#2c3a9f197ada23d145c884984315042d443a6bdc

**Comment by tejasmanohar** [comment]
2c3a9f197ada23d145c884984315042d443a6bdc

**Comment by santigimeno** [comment]
After doing some tests, the current approach was still failing depending on the date the tests were running on. I've tried to solve the issues in https://github.com/node-schedule/node-schedule/pull/94/
