### ISSUE TITLE
Method of persistence

### ISSUE THREAD

**Issue by tejasmanohar** [mattpat/node-schedule#90]
@jtmarmon suggested adding an option for a method of persistence w/ redis perhaps

we could add a couple options, maybe even filesystem persistence like crontab. any thoughts from the community?

**Comment by jagged3dge** [comment]
Apologies for reviving this old thread.
Persistence, even in a rudimentary crontab-ish file could go a long way when using this in services that auto-restart on app crash. It should be optional, of course.

As things stand now, we're having to write a wrapper around this module to automate reloading and persisting jobs. It would help if this was built into the module itself. 

Regardless, I'd understand if you want to keep the module light and to the point.

**Comment by vko-online** [comment]
Up :+1:  need sample

**Comment by ashwinreddymekala** [comment]
+1

**Comment by tejasmanohar** [comment]
discussion in #177

**Comment by scaryguy** [comment]
+1, I think this is a must be for most of serious production applications.

**Comment by tejasmanohar** [comment]
Locking comments here, please post in #177 

And yes, it is needed. I had to switch from node-schedule in my app due to multiple servers.
